### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by afreiberger** [juju/1.25-upgrade#66]
missing "github.com/juju/juju", "github.com/juju/collections" and "gopkg.in/juju/worker.v1" from dependencies.tsv.

Had to manually get these packages before make would succeed.
   go get github.com/juju/juju
   go get github.com/juju/collections
   go get gopkg.in/juju/worker.v1

commands/service.go:13:2: cannot find package "github.com/juju/juju/cmd/output" in any of:
	/snap/go/2130/src/github.com/juju/juju/cmd/output (from $GOROOT)
	/home/jujumanage/go/src/github.com/juju/juju/cmd/output (from $GOPATH)
juju2/worker/catacomb/catacomb.go:14:2: cannot find package "gopkg.in/juju/worker.v1" in any of:
	/snap/go/2130/src/gopkg.in/juju/worker.v1 (from $GOROOT)
	/home/jujumanage/go/src/gopkg.in/juju/worker.v1 (from $GOPATH)
make: *** [install] Error 1

**Comment by babbageclunk** [comment]
Thanks for this, I've added the worker dependency. The juju/juju and juju/collections dependencies shouldn't have been there, some code in the juju2 tree was still importing juju/juju (which in turn used juju/collections) rather than having been rewritten to import juju/1.25-upgrade/juju2.
